_wandb:
    value:
        cli_version: 0.26.1
        e:
            uinpf8b5y2a93ye2wep3wtwhhfqyl195:
                codePath: script/baseline.py
                codePathLocal: baseline.py
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "942328844288"
                        used: "162754682880"
                email: ashutosh24135@iiitd.ac.in
                executable: /home/ashutosh24135/miniconda3/envs/point-jepa/bin/python3
                git:
                    commit: 7677a543cbb1fd206a21080bb830f19837ec7ba8
                    remote: git@github.com:astral-fi/Point-JEPA.git
                gpu: NVIDIA A30
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-825bc740-91d3-16c3-2d66-044b721b3f99
                host: iras-hub
                memory:
                    total: "270126391296"
                os: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
                program: /home/ashutosh24135/Point-JEPA/script/baseline.py
                python: CPython 3.9.23
                root: /home/ashutosh24135/Point-JEPA/script
                startedAt: "2026-07-17T16:58:54.137515Z"
                writerId: uinpf8b5y2a93ye2wep3wtwhhfqyl195
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.23
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 64
dropout:
    value: 0.1
ff_dim:
    value: 512
lr:
    value: 0.0003
num_epochs:
    value: 100
num_heads:
    value: 2
num_layers:
    value: 8
token_dim:
    value: 128
warmup_epochs:
    value: 10
weight_decay:
    value: 0.01
